Sprint MartinKippenberger: Minor Improvements
ITISFoundation/osparc-issues pull request #1768
Opened 2024-10-29 13:50 UTC by mrnicegyu11

- Changes / Improves README.md
- Print sorted-by-dates in `scripts/3_deadlines_calendar.py`
- Check for github-API error-return-codes in `scripts/4_make_release_drafts.py`
- Minors

2024-10-29 13:56 UTC, GitHK reviewed
There is one big fishy thing

2024-10-29 13:56 UTC, GitHK commented on reviews/20241028_MartinKippenberger.md
why is this file here? Is it not wrong?

2024-10-29 13:56 UTC, GitHK commented on scripts/3_deadlines_calendar.py
> +{sorted_events}
I find this version way less readable. I preferred the declarative template approach.

2024-10-29 13:56 UTC, GitHK commented on scripts/6_app_team_email.py
> +- tip https://github.com/ITISFoundation/osparc-issues/blob/master/release-notes/tip/{vtag}.md
ahh they also have to handle tip now.

2025-08-04 07:10 UTC, mrnicegyu11 commented
@GitHK @matusdrobuliak66 should this minor enhancement PR be merged or should I close it? It is dangling....

2025-08-04 07:35 UTC, GitHK requested changes
I've re-reviewd this, but the old comments still apply. Please address them.

2025-08-04 07:35 UTC, GitHK commented on reviews/20241028_MartinKippenberger.md
@mrnicegyu11 please remove this file, I think it's a mistake

2025-08-04 07:35 UTC, GitHK commented on scripts/3_deadlines_calendar.py
> +{sorted_events}
And my comments here still apply. I think it's still less readable. Please keep the old format with whatever new edits you added

2025-08-04 07:39 UTC, mrnicegyu11 commented
ok thanks but no worries, I dont remember what I did here so it is not worth spending a lot of time, i will close it :--)

2025-08-04 07:39 UTC, closed without merging